module.exports = {
  env: {
    NEXT_PUBLIC_SITE_TITLE: process.env.NEXT_PUBLIC_SITE_TITLE,
    NEXT_PUBLIC_H1: process.env.NEXT_PUBLIC_H1,
    NEXT_PUBLIC_BANNER_IMG_URL: process.env.NEXT_PUBLIC_BANNER_IMG_URL,
    AIRTABLE_ENDPOINT: process.env.AIRTABLE_ENDPOINT,
    AIRTABLE_BASE_ID: process.env.AIRTABLE_BASE_ID,
    AIRTABLE_TABLE_NAME: process.env.AIRTABLE_TABLE_NAME,
    AIRTABLE_API_KEY: process.env.AIRTABLE_API_KEY,
  },
};
